### ISSUE TITLE
Impossible to change the chat box language

### ISSUE THREAD

**Issue by treighmawaka** [riderx/capacitor-crisp#1]
First off all, thanks for this great plugin!

**My issue:**

It is currently not possible to change the language used in the chat box on native devices. Crisp defaults to English. This is not an issue on the web as the browser correctly detects the user's language. Nonetheless, the ability to change the language would be very useful.

**Comment by riderx** [comment]
@treighmawaka thanks for the feedback!
i just sent a message to Crisp CEO @baptistejamin to check where that came from, and he told me they can help you on that!
In my side i have stop to use my this plugin since the iOS SDK don't have the same features as Web SDK.
instead i use iframe: 
https://help.crisp.chat/en/article/how-can-i-embed-the-crisp-chatbox-in-an-external-link-or-an-iframe-bkfh98/

**Comment by treighmawaka** [comment]
@riderx thanks for this. Truly appreciate it. I'll reach out to @baptistejamin  and also look into the iFrame solution

**Comment by riderx** [comment]
Did you find your issue ?

**Comment by treighmawaka** [comment]
> Did you find your issue ?

@riderx  I never had it fixed. I'm still using it with default options. Can you share how you handle it with iFrames?

**Comment by riderx** [comment]
yes you can find it there :
https://github.com/Forgr-ee/Mimesis/blob/main/src/services/crisp-web.ts
